### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by SuryayamSaha** [ViAsmit/YOLOv5-Flask#4]
FileNotFoundError: [WinError 2] The system cannot find the file specified
127.0.0.1 - - [24/Nov/2023 23:10:12] "POST /detect HTTP/1.1" 500 -

this error is showing

**Comment by SuryayamSaha** [comment]
Heres the full terminal



(venv) PS C:\Users\Suryayam Saha\Desktop\flask1\YOLOv5-Flask> flask run
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
<FileStorage: 'Screenshot 2023-11-12 143328.png' ('image/png')>
[2023-11-24 23:19:58,006] ERROR in app: Exception on /detect [POST]
Traceback (most recent call last):
  File "C:\Users\Suryayam Saha\Desktop\flask1\YOLOv5-Flask\venv\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Suryayam Saha\Desktop\flask1\YOLOv5-Flask\venv\lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Suryayam Saha\Desktop\flask1\YOLOv5-Flask\venv\lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Suryayam Saha\Desktop\flask1\YOLOv5-Flask\venv\lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Suryayam Saha\Desktop\flask1\YOLOv5-Flask\app.py", line 26, in detect
    subprocess.run("ls")
  File "C:\Program Files\Python310\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
127.0.0.1 - - [24/Nov/2023 23:19:58] "POST /detect HTTP/1.1" 500 -
